apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  namespace: tech-challenge-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-app
          image: hiagomarquesrubio/tech-challenge-hiago
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URL
              value: mongodb://mongodb:27017/techChallenge

---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  namespace: tech-challenge-namespace
spec:
  type: LoadBalancer
  selector:
    app: nodejs-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nodejs-app-hpa
  namespace: tech-challenge-namespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nodejs-app
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
